# =============================================================================
# fake_data.py - JSON-based data loader
# =============================================================================
# This module loads places and events from JSON files instead of having the
# data hardcoded in Python.
#
# When you have real data, you only need to:
#   1. Replace  data/places.json  with your real places  (same schema)
#   2. Replace  data/events.json  with your real events  (same schema)
#   3. Keep this file unchanged -- it just reads whatever JSON you provide.
#
# JSON SCHEMA  (matches entities_raw from the README -- every field required)
#
#   {
#     "entity_type":  "place" or "event",              required
#     "source":       "yelp", "osm", etc.,              required (use "fake" for demo)
#     "source_id":    "<id-from-source>",               required (unique within source)
#     "name":         "Display Name",                  required
#     "lat":          43.07,                           required  (float)
#     "lon":          -89.39,                          required  (float)
#     "address":      "123 Main St, Madison, WI",      required
#     "description":  "rich keyword text ...",         required (drives similarity)
#     "categories":   "tag1,tag2,tag3",                required (comma-separated)
#     "rating":       4.5,                            nullable  (null for events)
#     "review_count": 312,                            nullable  (null for events)
#     "price_tier":   2,                              nullable  (1-4, null if unknown)
#     "event_start":  "2026-02-28T12:00:00Z",         nullable  (null for places)
#     "event_end":    "2026-02-28T15:00:00Z"          nullable  (null for places)
#   }
#
# Notes:
#   - Datetime strings must be ISO 8601 (e.g. "2026-02-28T12:00:00Z").
#     Timezone suffix "Z" or "+00:00" is strongly recommended.
#   - entity_id, created_at, updated_at are auto-generated by the loader --
#     you do NOT need to include them in the JSON.
#   - The description field is the most important one: make it keyword-rich
#     (categories + vibe words + short summary) so TF-IDF similarity works.
#
# File paths (relative to this file's directory):
#   data/places.json   -- list of place objects
#   data/events.json   -- list of event objects
#
# Exposed functions:
#   get_fake_places()   ->  list[EntityRaw]
#   get_fake_events()   ->  list[EntityRaw]
#   get_all_entities()  ->  list[EntityRaw]   (places + events combined)

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from models import EntityRaw

# ---------------------------------------------------------------------------
# Paths to the JSON files
# ---------------------------------------------------------------------------

# os.path.abspath(__file__) gives the absolute path to THIS file.
# Resolving relative to it means the project works no matter which
# directory you launch the server or demo from.
_HERE       = os.path.dirname(os.path.abspath(__file__))
_DATA_DIR   = os.path.join(_HERE, "data")
PLACES_FILE = os.path.join(_DATA_DIR, "places.json")
EVENTS_FILE = os.path.join(_DATA_DIR, "events.json")

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _parse_datetime(value: Optional[str]) -> Optional[datetime]:
    """
    Parse an ISO 8601 datetime string into a timezone-aware datetime object.

    Accepts formats like:
        "2026-02-28T12:00:00Z"
        "2026-02-28T12:00:00+00:00"
        "2026-02-28T12:00:00"    <- assumed UTC if no timezone suffix

    Returns None if value is None or empty string.
    """
    if not value:
        return None

    # Replace trailing "Z" with "+00:00" so Python fromisoformat() handles it.
    # Python < 3.11 does not understand the "Z" suffix natively.
    iso_str = value.strip().replace("Z", "+00:00")

    try:
        dt = datetime.fromisoformat(iso_str)
    except ValueError:
        # Fallback: try the most common bare format
        dt = datetime.strptime(value.strip(), "%Y-%m-%dT%H:%M:%S")

    # If still naive (no tzinfo), assume UTC
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)

    return dt


def _load_json_file(filepath: str) -> List[Dict[str, Any]]:
    """
    Read a JSON file and return its contents as a Python list of dicts.
    Raises a clear FileNotFoundError if the file does not exist.
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(
            f"Data file not found: {filepath}\n"
            f"Create it (or symlink your real data file) at that path."
        )
    with open(filepath, "r", encoding="utf-8") as f:
        return json.load(f)


def _row_to_entity(row: Dict[str, Any]) -> EntityRaw:
    """
    Convert one JSON row (dict) into an EntityRaw dataclass instance.

    Only the fields in the schema comment above are needed in the JSON.
    entity_id, created_at, and updated_at are auto-generated here so
    callers do not have to include them.
    """
    return EntityRaw(
        # Auto-generated fields -- NOT required in the JSON
        entity_id   = EntityRaw.make_id(),
        created_at  = datetime.now(timezone.utc),
        updated_at  = datetime.now(timezone.utc),

        # Required string / numeric fields
        entity_type  = row["entity_type"],
        source       = row["source"],
        source_id    = row["source_id"],
        name         = row["name"],
        lat          = float(row["lat"]),
        lon          = float(row["lon"]),
        address      = row["address"],
        description  = row["description"],

        # categories is optional; defaults to empty string if omitted
        categories   = row.get("categories", ""),

        # Nullable fields -- .get() returns None when the key is absent
        rating       = row.get("rating"),
        review_count = row.get("review_count"),
        price_tier   = row.get("price_tier"),

        # Datetime fields (ISO 8601 strings in JSON; None for places)
        event_start  = _parse_datetime(row.get("event_start")),
        event_end    = _parse_datetime(row.get("event_end")),
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_fake_places() -> List[EntityRaw]:
    """
    Load places from  data/places.json  and return them as EntityRaw objects.

    To swap in real data: replace data/places.json -- schema stays the same.
    """
    rows = _load_json_file(PLACES_FILE)
    return [_row_to_entity(row) for row in rows]


def get_fake_events() -> List[EntityRaw]:
    """
    Load events from  data/events.json  and return them as EntityRaw objects.

    To swap in real data: replace data/events.json -- schema stays the same.
    Event rows must have ISO 8601 strings in event_start and event_end.
    """
    rows = _load_json_file(EVENTS_FILE)
    return [_row_to_entity(row) for row in rows]


def get_all_entities() -> List[EntityRaw]:
    """
    Return all places + events as one combined list.
    This is the entry point used by pipeline.py.
    """
    return get_fake_places() + get_fake_events()
